deployment:
  enabled: true
  name: orders
  namespace: ecommerce
  replicas: 1
  appName: orders
  role: api
  containerName: orders-container
  image:
    repository: harbor.192.168.1.101.nip.io:8443/tester/test-image
    tag: 0.3.22
  service:
    port: 3003

# Reference to existing secrets
secrets:
  usernameSecret: "harbor-release-core"  # Name of the secret
  usernameKey: "HARBOR_USERNAME"          # Key in the secret
  passwordSecret: "harbor-release-core"    # Name of the secret
  passwordKey: "HARBOR_ADMIN_PASSWORD"     # Key in the secret
  tlsSecret: "harbor-release-core"          # Name of the secret for TLS
  tlsCertKey: "tls.crt"                    # Key for the certificate
  tlsKeyKey: "tls.key"                     # Key for the private key
