deployment:
  enabled: true
  name: orders
  namespace: ecommerce 
  replicas: 1
  appName: orders
  role: api
  containerName: orders-container
  port: 3003

image:
  repository: harbor.192.168.1.101.nip.io:8443/tester/test-image
  tag: 0.3.19
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: harbor-registry-secret
