deployment:
  enabled: true
  name: orders
  namespace: cattle-monitoring-system
  replicas: 1
  appName: orders
  role: api
  containerName: orders-container
  imageRepository: harbor.192.168.1.101.nip.io:8443/tester/test-image
  imageTag: 0.3.21
  port: 3003
