# Deployment object
deployment:
  enabled: true
  name: graphql
  namespace: ecommerce
  replicas: 3
  appName: graphql
  role: api
  containerName: graphql-container
  imageRepository: lukondefmwila/ecommerce-graphql
  imageTag: "0.1.5"
  port: 3002
# Service object
service:
  enabled: true
  name: graphql-service
  namespace: ecommerce
  appName: graphql
  type: LoadBalancer
  servicePort: 3002
  targetPort: 3002
# Service Account object
serviceAccount:
  enabled: true
  name: graphql-service-account
  namespace: ecommerce
# Namespace object
namespace:
  enabled: false
# Ingress 
ingress:
  enabled: false
